### ISSUE TITLE
Errors and spanish translation

### ISSUE THREAD

**Issue by zuhir** [ConfusedAlex/GoldEconomy#22]
When i use "bank add" and "bank remove" in console i get this: (purpur version: git-Purpur-1882 (MC: 1.19.3))

bank remove zuhir__ 1
[17:26:36 WARN]: java.lang.reflect.InvocationTargetException
[17:26:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
[17:26:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[17:26:36 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.runHook(Command.java:799)
[17:26:36 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.execute(Command.java:697)
[17:26:36 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.execute(Command.java:709)
[17:26:36 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command$1.execute(Command.java:444)
[17:26:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:26:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975)
[17:26:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:938)
[17:26:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:536)
[17:26:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[17:26:36 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[17:26:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[17:26:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:26:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[17:26:36 WARN]: Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @3d012ddd)
[17:26:36 WARN]:        at TheGoldEconomy.jar//confusedalex.thegoldeconomy.Commands.remove(Commands.java:157)
[17:26:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[17:26:36 WARN]:        ... 14 more

bank add zuhir__ 1
[17:24:16 WARN]: java.lang.reflect.InvocationTargetException
[17:24:16 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
[17:24:16 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[17:24:16 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.runHook(Command.java:799)
[17:24:16 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.execute(Command.java:697)
[17:24:16 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command.execute(Command.java:709)
[17:24:16 WARN]:        at TheGoldEconomy.jar//redempt.redlib.commandmanager.Command$1.execute(Command.java:444)
[17:24:16 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:24:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975)
[17:24:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:938)
[17:24:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:536)
[17:24:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[17:24:16 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[17:24:16 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[17:24:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:24:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[17:24:16 WARN]: Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @3d012ddd)
[17:24:16 WARN]:        at TheGoldEconomy.jar//confusedalex.thegoldeconomy.Commands.add(Commands.java:148)
[17:24:16 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[17:24:16 WARN]:        ... 14 more

Also i translated plugin to spanish:

messages
info.balance = &fTienes &6%d&f de Oro (Banco: &6%d&f | Inventario: &6%d&f)
info.withdraw = &fHas retirado &6%d&f de Oro.
info.deposit = &fHas depositado &6%d&f de Oro.
info.sendmoneyto = ¡Has enviado &6%d&f de Oro a %s!
info.moneyreceived = ¡Has recibido &6%d de Oro &fde %s!
info.sender.moneyset = ¡Saldo de %s establecido a &6%d&f de Oro!
info.target.moneyset = ¡Tu saldo ha sido establecido a &6%d&f de Oro!
info.sender.addmoney = ¡Agregado(s) &6%d&f de Oro al saldo de %s!
info.target.addmoney = ¡&6%d&f de Oro agregado(s) a tu saldo!
info.sender.remove = ¡Eliminado(s) &6%d&f de Oro del saldo de %s!
info.target.remove = ¡&6%d&f de Oro eliminado(s) de tu saldo!
help.deposit = ¡Debes especificar cuanto Oro quieres depositar! Uso: /bank deposit <gold | all>
help.withdraw = ¡Debes especificar cuanto Oro quieres retirar! Uso: /bank withdraw <gold | all>
warning.update = &fEstás usando una versión desactualizada del plugin. Por favor actualiza a la última versión.
warning.drops = &f¡Algunos articulos fueron arrojados al piso! &7(inventario lleno)
error.bankplot = ¡Debes estar en una Parcela Bancaria para usar ese comando!
error.noplayer = ¡Jugador no encontrado!
error.zero = ¡No puedes retirar o depositar 0 de Oro!
error.negative = ¡No puedes retirar, depositar o transferir una cantidad negativa de Oro!
error.notenough = ¡No tienes suficiente Oro!
error.payyourself = ¡No puedes enviarte Oro a ti mismo!
error.notenoughmoneywithdraw = ¡No puedes transferir más Oro del que tienes!

command-format:
helpTitle: &a--[ &eAyuda para %cmdname% &a]--
helpEntry: &e%cmdname%&a: %help%
helpTextColor: &a
noPermission: &c¡No tienes permiso para ejecutar ese comando! (%permission%)
mustHoldItem: &c¡Debes tener un articulo en la mano para hacer eso!
playerOnly: &c¡Ese comando solo puede ser ejecutado por un jugador!
consoleOnly: &c¡Ese comando solo puede ser ejecutado por la consola!
invalidArgument: &cArgumento invalido para %arg%: %value%
needArgument: &cDebes dar al menos un argumento para %arg%
needFlagValue: &cDebes dar un valor para la propiedad %flag%
wrongArgumentCount: &cNúmero incorrecto de argumentos. Argumento(s) esperado(s) %args%, obtenidos %count%
invalidSubcommand: &cSubcomando invalido: %value%
contextDefaultFromConsole: &cNo se puede inferir el valor predeterminado del argumento %arg% para el remitente de la consola, por favor especifiquelo.
contextDefaultFlagFromConsole: &cNo se puede inferir el valor predeterminado de la propiedad %flag% para el remitente de la consola, por favor especifiquelo.
ambiguousOptional: &cHay al menos un argumento opcional ambiguo, por favor intentelo de nuevo sin omitir argumentos.
commandError: &cHa ocurrido un error al ejecutar el comando. Por favor contacta a un administrador.
showUsage: &cUso: %usage%
numberOutsideRange: &cNúmero fuera del rango permitido: %range%

**Comment by ConfusedAlex** [comment]
Hey first, thanks for reporting this Issue! I will fix and update tonight!

Also very thanks for the Spanish translation! It is so motivating to see that People are using my plugin :)
Can I give you credits on the ReadMe Page?

**Comment by zuhir** [comment]
> Hey first, thanks for reporting this Issue! I will fix and update tonight!
> 
> Also very thanks for the Spanish translation! It is so motivating to see that People are using my plugin :) Can I give you credits on the ReadMe Page?

Sure, no problem
