### ISSUE TITLE
Java Exception

### ISSUE THREAD

**Issue by ElSantoSuper** [ConfusedAlex/GoldEconomy#7]
Just noticed this in the console when I restarted my server:

`[27.06 12:40:36] [Server] [WARN] [TheGoldEconomy] Plugin TheGoldEconomy v1.4 generated an exception while executing task 11
[27.06 12:40:36] [Server] java.util.MissingResourceExceptionCan't find resource for bundle java.util.PropertyResourceBundle, key info.update
[27.06 12:40:36] [Server] 	at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
[27.06 12:40:36] [Server] 	at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
[27.06 12:40:36] [Server] 	at confusedalex.thegoldeconomy.TheGoldEconomy.lambda$onEnable$1(TheGoldEconomy.java:63) ~[TheGoldEconomy.jar:?]
[27.06 12:40:36] [Server] 	at confusedalex.thegoldeconomy.UpdateChecker.lambda$getVersion$0(UpdateChecker.java:28) ~[TheGoldEconomy.jar:?]
[27.06 12:40:36] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-39]
[27.06 12:40:36] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-39]
[27.06 12:40:36] [Server] 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
[27.06 12:40:36] [Server] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[27.06 12:40:36] [Server] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
[27.06 12:40:36] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by ConfusedAlex** [comment]
Are you on the latest version 1.4.1?

**Comment by ConfusedAlex** [comment]
I think this might be a bug I fixed today.
